---
- name: check for bobby
  hosts: all
  connection: winrm
  gather_facts: false
  tasks:
    - name: Ensure user bob is present with address information
      community.windows.win_domain_user:
        name: bobaardappel
        firstname: Aardbob
        surname: Smith
        company: BobCo
        password: B0bP4ssw0rd
        state: present
        path: CN=Users,DC=peeps,DC=piepers
        groups:
          - Domain Users
          - Domain Admins
        street: 123 4th St.
        city: Sometown
        state_province: IN
        postal_code: 12345
        country: US
        attributes:
          telephoneNumber: 555-123456
