---
- name: Detect Newhosts Within network And put them into an Inventory
  hosts: localhost
  connection: local
  tasks:

    - name: Add AwX inventory for PXE clients
      tower_inventory:
        name: "PXE clients"
        description: "Inventory for pxe Clients"
        organization: "Doekoe.local"
        state: present


    - name: Scan for hosts
      community.general.nmap:
        plugin: community.general.nmap
        strict: False
        address: 39.0.0.0/24