#trying to invoke powershell crap in ansible so that we can do all kinds of awesome things 
# We enjoy doing kinda awesome things like voquein
---
- name: invoke SQL powershell
  hosts: all
  connection: winrm
  tasks:
    - name: Create user
      win_shell: |
        $data = Invoke-Sqlcmd -Query "SELECT * FROM [Challenge].[dbo].[user2]" -ServerInstance "srv-winess19"        
        foreach($employee in $data)
        {
        write-output $employee

        if ($employee.state -eq "False")
        {
        write-output "Dit is Kut en Raar"

        Remove-ADUser -Identity $employee.username

        }
        
        ElseIf ($employee.state -eq "True") 
        {
        Write-output "Deze statemennt was TRUE en ik ga nu " + $employee.username  + " aanmaken"  
        function Get-RandomCharacters($length, $characters) 
        {
        $random = 1..$length | ForEach-Object { Get-Random -Maximum $characters.length }
        $private:ofs=""
        return [String]$characters[$random]
        }
        function Scramble-String([string]$inputString)
        {     
        $characterArray = $inputString.ToCharArray()   
        $scrambledStringArray = $characterArray | Get-Random -Count $characterArray.Length     
        $outputString = -join $scrambledStringArray
        return $outputString 
        }
 
        $password = Get-RandomCharacters -length 5 -characters 'abcdefghiklmnoprstuvwxyz'
        $password += Get-RandomCharacters -length 1 -characters 'ABCDEFGHKLMNOPRSTUVWXYZ'
        $password += Get-RandomCharacters -length 1 -characters '1234567890'
        $password += Get-RandomCharacters -length 1 -characters '!'
 
        Write-Host $password

        $password = Scramble-String $password
 
        Write-Host $password

        $SecurePassword = $password | ConvertTo-SecureString -AsPlainText -Force

        New-ADUser -Name $employee.username -GivenName $employee.firstname -Surname $employee.lastname -SamAccountName $employee.username -Path "CN=Users,DC=peeps,DC=piepers" -Company $employee.company -City $employee.city -AccountPassword $SecurePassword -Enabled $True
        Invoke-Sqlcmd -Query "UPDATE Challenge.dbo.user2 SET creation = 0 WHERE ID = $($employee.ID) " -ServerInstance "srv-winess19"  -OutputSqlErrors $True
        Invoke-Sqlcmd -Query "INSERT INTO Challenge.dbo.passwords (ID,Username,Password) VALUES ($($employee.ID), '$($employee.username)', '$($password)');" -ServerInstance "srv-winess19"  -OutputSqlErrors $True
        }
        } 