#trying to invoke powershell crap in ansible so that we can do all kinds of awesome things 
# We enjoy doing kinda awesome things like voquein
---
- name: invoke SQL powershell
  hosts: all
  connection: winrm
  gather_facts: false
  tasks:
    - name: Invoke SQL Read sql table data
      ansible.windows.win_shell:  ||
      Read-SqlTableData -ServerInstance "srv-winess19" -DatabaseName "Challenge" -SchemaName "dbo" -TableName "user" -TopN 3