#trying to invoke powershell crap in ansible so that we can do all kinds of awesome things 
# We enjoy doing kinda awesome things like voquein
---
- name: invoke SQL powershell
  hosts: all
  connection: winrm
  tasks:
     - name: execute a PowerShell command on remote 
      Windows hosts
      win_command: (get-service wuauserv | select status 
       | Format-Wide | Out-String).trim()
      register: output
 
    - debug: var=output.stdout