#trying to invoke powershell crap in ansible so that we can do all kinds of awesome things 
# We enjoy doing kinda awesome things like voquein

# Even morgen kijken of het mogelijk is om data op te laten slaan tussen de dingen heen waarschijnlijk wel
---
- name: Onboarding and offboarding of personal
  hosts: all
  tasks:

    - name: Gathering SQL data for users that need to be Created


    - name: Creating users
      win_shell: |
        $data = Invoke-Sqlcmd -Query "SELECT * WHERE creation = True FROM [Testenv].[dbo].[user2]" -ServerInstance "srv-winess19"
        foreach($employee in $data){
        [int] $inc = 0
          if (Get-ADuser -Filter {SamAccountName -eq "$employee.username"}) 
          {    
            do 
             {
                $inc ++
                $Username = $employee.username + [string]$inc
             } 
            until (-not (Get-ADuser -Filter {SamAccountName -eq "$Username"}))
          }
          New-ADUser -Name $username `
          -GivenName $employee.firstname `
          -Surname $employee.lastname `
          -SamAccountName $employee.username `
          -Path Employee.path `
          -Company $employee.company `
          -City $employee.city `
          -Enabled $False
        }

    - name: Creating User Home Folder

    - name: Gatherng SQL data for user that have to be Deleted

    - name: Disabling users
      win_shell: /
        $data = Invoke-Sqlcmd -Query "SELECT * WHERE creation = FALSE FROM [Testenv].[dbo].[user2]" -ServerInstance "srv-winess19"
        foreach($employee in $data){
          Disable-ADAccount -Identity $employee.username
          }
        }

