### Oefening about passing through Powershell Variables Between Playbook tasks
#Yaml working with different Varables 
#Passing Variables through Different Tasks within a playthrough
---
- name: Parsing Powershell Variables between multiple tasks in the Ansible Playbook
  hosts: win-testenv1.TESTENV.DOEKOE.LOCAL
  tasks:

  - name: run an executable using win_command
    win_command: whoami
      register: Variable1

  - name: show variable
    debug: 
      var: Variable1
      verbosity: 4