### Oefening about passing through Powershell Variables Between Playbook tasks
#Yaml working with different Varables 
#Passing Variables through Different Tasks within a playthrough
---
- name: Parsing Powershell Variables between multiple tasks in the Ansible Playbook
  hosts: win-testenv1.TESTENV.DOEKOE.LOCAL
  gather_facts: no
  tasks:

    - name: Get Variable1
      win_shell: |
        whoami 
      register: Variable1

    - name: type that shit
      win_shell: |
        param(
        [string]$Name = $arg[0]
        )

        write $Name
      stdin: Variable1
