---
- hosts: all
  vars:
    - ansible_password: "Doekoe2020!"
    - public_key: "{{ lookup('file', '/home/ansible-op/.ssh/id_rsa.pub') }}"
  gather_facts: no
  become: yes
  tasks:

    - name: Disable Password Authentication for all users
      lineinfile:
          path=/etc/ssh/sshd_config
          regexp='^PasswordAuthentication'
          line="PasswordAuthentication no"
          state=present
          backup=yes

    - name: Enable Password Authenticaiton for Sysop Users
      blockinfile: |
      path=/etc/ssh/sshd_config
      insertafter='^PasswordAuthentication'
      content="Match sysop
          PasswordAuthentication yes"
      state=present 
      

   - name: Disable Root Login
      lineinfile:
          path=/etc/ssh/sshd_config
          regexp='^PermitRootLogin'
          line="PermitRootLogin no"
          state=present
          backup=yes
      notify:
        - restart ssh
        

   handlers:
   - name: restart ssh
       service:
        name=sshd
        state=restarted