---
- hosts: all
  vars:
    - ansible_password: '{{LPassword}}'
  gather_facts: no
  remote_user: sysop
  become: true
  tasks:
    - name: Creating user and adding him to web-devevelopers
      user:
        name: "Ansible-op"