---
- hosts: all
  vars:
    - ansible_password: "Doekoe2020!"
    - public_key: "{{lookup('file', '/home/ansible-op/.ssh/id_rsa.pub')}}"
  gather_facts: no
  become: true
  tasks:

    - name: Creating the user ansible-op
      user:
        name: "ansible-op"

    - name: Add ansiblebot user to the sudoers
      copy:
        dest: "/etc/sudoers.d/ansible-op"
        content: "ansible-op  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key to remote Machine
        ansible.posix.authorized_key: user= ansible-op
                                      key= "{{ public_key }}"
                                      state= present