---
- name: Provision Projects And Departments in a few Clicks
  hosts: all
  

  tasks:


  - name: Creat OU for New department
    local_deploy_user:
      action: create
      firstname: bob
      lastname: test
      oupath: OU=Employee,OU=Human-Recources,OU=People,OU=EU,DC=Aspire,DC=local
      sharepath: \\aspire-server\eu-fileserver\People
      groups:
        - test1
        - test2
        - test3